#!/bin/sh
# Copyright (C) 2014 Alexander Couzens

. /usr/lib/preinit-flasher/lib

preinit_flasher_try() {
  local address="$1"
  local interface="$2"
  if [ ! -d /sys/class/net/${interface} ] ; then
    return
  fi

  modprobe ipv6
  sleep 3

  if [ "${address%%:*}" == "fe80" ] ; then
    address="${address}%${interface}"
  fi

  ping -6 -c 2 -W 2 -I $interface ${address}
  if [ $? -ne 0 ] ; then
    return
  fi

  # dont preserve configuration
  preinit_flasher_wget_image "http://[${address}]/preinit/$(cat /sys/class/net/${interface}/address)" no
}

preinit_flasher_flasher() {
  for iface in $(ls /sys/class/net/) ; do
    [ "$iface" == "lo" ] && continue
    preinit_flasher_try fe80::08ef:2342 $iface
  done
}

boot_hook_add preinit_main preinit_flasher_flasher

