#!/bin/sh
# Copyright (C) 2014 Alexander Couzens

lazus_try() {
    local interface=$1
    local address='fe80::08ef:2342'
    if [ ! -d /sys/class/net/${interface} ] ; then
        return
    fi

    modprobe ipv6
    sleep 3

    ping -6 -c 2 -W 2 -I $interface ${address}%${interface}

    if [ $? -ne 0 ] ; then
        return
    fi
    
    wget -T 3 -O /tmp/image.gpg http://[${address}%${interface}]/preinit/$(cat /sys/class/net/${interface}/address)
    if [ $? -eq 0 ] ; then
        lazus_do_sysupgrade
    fi
}

lazus_do_sysupgrade() {
    gpg --ignore-time-conflict --batch -q --homedir /tmp/ --import /usr/lib/lazus-preinit-flasher/image.asc
    gpg --ignore-time-conflict --batch -q --homedir /tmp/ --verify /tmp/image.gpg
    if [ $? -eq 0 ] ; then
        gpg --ignore-time-conflict --batch -q --homedir /tmp/ -o /tmp/image.bin -d /tmp/image.gpg
        sysupgrade -n /tmp/image.bin
    fi
}

lazus_flasher() {
    for iface in $(ls /sys/class/net/) ; do
        [ "$iface" == "lo" ] && continue
        lazus_try $iface
    done
}

boot_hook_add preinit_main lazus_flasher

